language: java
jdk:
  - openjdk8

# CI를 어떤 브랜치에 push할 때 수행하는지 브랜치 지정
branches:
  only:
    - master

# Travis CI 서버의 Home
# 같은 의존성은 다음 배포 때부터 다시 다운받지 않도록 캐싱
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'



# CI 수행 스크립트 : master 브랜치에 push되었을 때, 빌드 수행
script: "./gradlew clean build"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - yjchoi7166@gmail.com